# Menus
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  GitHub: https://github.com/huotaihe
  About: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        fixed: true
        avatar: css/images/avatar.png
        gravatar: hersbit@yeah.net # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: 白马度和
        author_title: 不断努力着 & 和太贺
        location: Shanghai, China
        follow: https://github.com/huotaihe
    highlight: tomorrow
    sidebar: right # sidebar position, options: left, right or leave it empty
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: favicon.png # path to favicon
    social_links:
        github: http://github.com/ppoffice/hexo-theme-icarus
        twitter: /
        facebook: /
        dribbble: /
        rss: /
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus:  # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # enter the domain name of your own comment isso server eg. comments.example.com
    changyan: # please fill in `appid` and `conf` to enable
        appid:
        conf:
    gitment:
        owner: huotaihe
        repo: huotaihe.github.io
        #Register an OAuth application, and you will get a client ID and a client secret.
        client_id: 67d4fdced7522e210c75
        client_secret: 1539dd9d89d920309cce0c5f45510d7af4607acb
    livere: # enter livere uid here
    valine: # Valine Comment System https://github.com/xCss/Valine
        on:  # enter true to enable
        appId:  # enter the leancloud application appId here
        appKey: # enter the leancloud application appKey here
        notify: # enter true to enable <Mail notifier> https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
        verify: # enter true to enable <Validation code>
        placeholder: Just Do It # enter the comment box placeholder
    

# Share
share: bdshare # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: 3c72d1bbe07baab58256c46951b76fd8
    mathjax: true # options: true, false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
#版权信息
copyright:
    enable: true
    # img: http://ostu98x74.bkt.clouddn.com/copyright/copyright.png #版权信息图片
    site: http://www.huotaihe.com  #版权信息所属网址
    siteName: 白马度和|Huotaihe #版权信息网站名字
    siteAuthor: '白马度和' #版权归属人

#是否开启打赏
donate: 
    enable: true
    message: 欣赏此文？求鼓励，求支持！
    pay:
        wechat: /css/images/wechatpay.png
        alipay: /css/images/alipay.png

